# Generated by Django 3.0.8 on 2020-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
